#!/bin/bash
# FlowOS Columbia Basin - Alpha Developer Test
# RootFilesystem (RootFS) Initilization Script

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
export HOME=/root
export TERM=xterm-256color

# INTERNAL TODO: Need to create a function to fetch build codename, string, and version no.
echo "Starting FlowOS Columbia Basin - rootFS initalizing....."

# Mount sysroot filesystems
echo "[DiskMGMT] Mounting rootfs /proc (rootFS)....."
mount -n -t proc proc /proc
echo "[DiskMGMT] Mounting /sys (rootFS)....."
mount -n -t sysfs sysfs /sys
echo "[DiskMGMT] Mounting /dev (rootFS)....."
mount -t devtmpfs dev /dev
echo "[DiskMGMT] Mounting /run (rootFS)....."
mount -n -t tmpfs tmpfs /run

# Start udev EWWW UDEV
#if [ -x /usr/lib/systemd/systemd-udevd ]; then
#    echo "[init] starting udevd"
#    /usr/lib/systemd/systemd-udevd --daemon
#    udevadm trigger --action=add
#    udevadm settle
#elif [ -x /sbin/udevd ]; then
#    echo "[init] starting udevd (standalone)"
#    /sbin/udevd --daemon
#    udevadm trigger --action=add
#    udevadm settle
#else
#    echo "[init] WARNING: udev not found"
#fi

echo "[NetworkSTCK] Setting hostname to:" && echo "$(cat /etc/hostname)" && echo "....."
[ -f /etc/hostname ] && hostname "$(cat /etc/hostname)"

# Mount all filesystems that are defined in /etc/fstab
echo "[DiskMGMT] Mounting devices defined in /etc/fstab"
mount -a || echo "[DiskMGMT] *WARNING* mount -a failed"

# Set ip addr loopback
echo "[NetworkSTCK] Setting up lo interface....."
ip link set lo up 2>/dev/null

# Set up additional network interfaces (should be located in an file in the future)
#ip addr add 192.168.100.2/24 dev eth0
echo "[NetworkSTCK] Starting Network Interface devices....."
ip link set eth0 up
echo "[NetworkSTCK] Registering IP Tables....."
ip route add default via 192.168.1.1 # set origin route
echo "[NetworkSTCK] Starting DHCP client (dhcpcd)....."
dhcpd eth0 --rebind

# Exit into userspace and spawn getty
echo "[UserSpace] Booting into bash....."

/bin/bash
#exec /sbin/agetty --noclear tty1 linux
